{% set name = "datamodel-code-generator" %}
{% set version = "0.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datamodel_code_generator-{{ version }}.tar.gz
  sha256: 3b360d7902d682ea011d5711b1037ba4dcf1b3b6b5f56bc39ed7f5aed51facb6

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - datamodel-codegen=datamodel_code_generator.__main__:main

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - python >=3.7,<4.0
  run:
    - argcomplete >=1.10,<4.0
    - black >=19.10b0
    - genson >=1.2.1,<2.0
    - inflect >=4.1.0,<6.0
    - isort >=4.3.21,<6.0
    - jinja2 >=2.10.1,<4.0
    - openapi-spec-validator >=0.2.8,<=0.5.1
    - packaging
    - prance >=0.18.2,<1.0
    - pydantic >=1.5.1,<2.0
    - python >=3.7,<4.0
    - pysnooper >=0.4.1,<2.0.0
    - toml >=0.10.0,<1.0.0

test:
  imports:
    - datamodel_code_generator
  commands:
    # Cannot run pip check because prance version is broken
    # - pip check
    - datamodel-codegen --help
  requires:
    - pip

about:
  home: https://github.com/koxudaxi/datamodel-code-generator
  doc_url: https://koxudaxi.github.io/datamodel-code-generator/
  summary: Pydantic model and dataclasses.dataclass generator for easy conversion of JSON, OpenAPI, JSON Schema, and YAML data sources.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
